# pytest.ini
[pytest]
# Adds the root directory to the python path 
pythonpath = .

# Default command line options: 
# -v: verbose output (shows test names)
# -s: allows print() statements to show in the console
addopts = -v -s

# Tells pytest where to look for tests
testpaths =
    tests